
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 25 01:22:42 UTC 2014
//----------------------------------------------------

import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Thu Dec 25 01:22:42 UTC 2014
  */
public class CoolParser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public CoolParser() {super();}

  /** Constructor which sets the default scanner. */
  public CoolParser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\062\000\002\003\003\000\002\002\004\000\002\004" +
    "\003\000\002\004\004\000\002\005\010\000\002\005\012" +
    "\000\002\005\004\000\002\006\002\000\002\006\003\000" +
    "\002\006\004\000\002\007\014\000\002\007\006\000\002" +
    "\007\010\000\002\007\004\000\002\010\002\000\002\010" +
    "\003\000\002\010\005\000\002\011\005\000\002\012\002" +
    "\000\002\012\003\000\002\012\005\000\002\013\004\000" +
    "\002\013\005\000\002\015\003\000\002\015\004\000\002" +
    "\016\010\000\002\014\010\000\002\014\012\000\002\014" +
    "\006\000\002\014\005\000\002\014\005\000\002\014\005" +
    "\000\002\014\005\000\002\014\005\000\002\014\004\000" +
    "\002\014\005\000\002\014\005\000\002\014\005\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\004\000\002\014\004\000\002\014\011" +
    "\000\002\014\007\000\002\014\005\000\002\014\005\000" +
    "\002\014\004\000\002\014\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\006\003\006\004\010\001\002\000\010\002" +
    "\001\003\006\004\010\001\002\000\004\002\200\001\002" +
    "\000\004\043\177\001\002\000\010\002\uffff\003\uffff\004" +
    "\uffff\001\002\000\004\055\011\001\002\000\006\011\013" +
    "\050\012\001\002\000\010\003\016\051\ufffa\056\021\001" +
    "\002\000\004\055\014\001\002\000\004\050\015\001\002" +
    "\000\010\003\016\051\ufffa\056\021\001\002\000\004\043" +
    "\173\001\002\000\010\003\ufff9\051\ufff9\056\ufff9\001\002" +
    "\000\010\003\016\051\171\056\021\001\002\000\006\044" +
    "\022\045\023\001\002\000\004\055\163\001\002\000\010" +
    "\042\ufff3\046\ufff3\056\025\001\002\000\006\042\031\046" +
    "\032\001\002\000\004\044\027\001\002\000\006\042\ufff2" +
    "\046\ufff2\001\002\000\004\055\030\001\002\000\006\042" +
    "\ufff0\046\ufff0\001\002\000\004\056\025\001\002\000\004" +
    "\044\033\001\002\000\004\055\034\001\002\000\004\050" +
    "\035\001\002\000\034\007\044\017\036\020\047\024\040" +
    "\025\045\027\051\041\052\045\053\050\037\052\042\053" +
    "\041\054\043\056\046\001\002\000\034\007\044\017\036" +
    "\020\047\024\040\025\045\027\051\041\052\045\053\050" +
    "\037\052\042\053\041\054\043\056\046\001\002\000\034" +
    "\007\044\017\036\020\047\024\040\025\045\027\051\041" +
    "\052\045\053\050\037\052\042\053\041\054\043\056\046" +
    "\001\002\000\004\055\147\001\002\000\050\005\uffdb\006" +
    "\uffdb\014\uffdb\015\uffdb\016\uffdb\022\uffdb\030\uffdb\032\uffdb" +
    "\033\uffdb\034\uffdb\035\uffdb\036\uffdb\037\uffdb\040\uffdb\042" +
    "\uffdb\043\uffdb\046\uffdb\047\uffdb\051\uffdb\001\002\000\050" +
    "\005\uffda\006\uffda\014\uffda\015\uffda\016\uffda\022\uffda\030" +
    "\uffda\032\uffda\033\uffda\034\uffda\035\uffda\036\uffda\037\uffda" +
    "\040\uffda\042\uffda\043\uffda\046\uffda\047\uffda\051\uffda\001" +
    "\002\000\050\005\uffd8\006\uffd8\014\uffd8\015\uffd8\016\uffd8" +
    "\022\uffd8\030\uffd8\032\uffd8\033\uffd8\034\uffd8\035\uffd8\036" +
    "\uffd8\037\uffd8\040\uffd8\042\uffd8\043\uffd8\046\uffd8\047\uffd8" +
    "\051\uffd8\001\002\000\034\007\044\017\036\020\047\024" +
    "\040\025\045\027\051\041\052\045\053\050\037\052\042" +
    "\053\041\054\043\056\046\001\002\000\034\007\044\017" +
    "\036\020\047\024\040\025\045\027\051\041\052\045\053" +
    "\050\037\052\042\053\041\054\043\056\046\001\002\000" +
    "\054\005\uffd9\006\uffd9\014\uffd9\015\uffd9\016\uffd9\022\uffd9" +
    "\026\134\030\uffd9\032\uffd9\033\uffd9\034\uffd9\035\uffd9\036" +
    "\uffd9\037\uffd9\040\uffd9\042\uffd9\043\uffd9\045\133\046\uffd9" +
    "\047\uffd9\051\uffd9\001\002\000\034\007\044\017\036\020" +
    "\047\024\040\025\045\027\051\041\052\045\053\050\037" +
    "\052\042\053\041\054\043\056\046\001\002\000\026\030" +
    "\061\032\057\033\063\034\055\035\056\036\060\037\066" +
    "\040\062\047\065\051\115\001\002\000\034\007\044\017" +
    "\036\020\047\024\040\025\045\027\051\041\052\045\053" +
    "\050\037\052\042\053\041\054\043\056\046\001\002\000" +
    "\034\007\044\017\036\020\047\024\040\025\045\027\051" +
    "\041\052\045\053\050\037\052\042\053\041\054\043\056" +
    "\046\001\002\000\034\007\044\017\036\020\047\024\040" +
    "\025\045\027\051\041\052\045\053\050\037\052\042\053" +
    "\041\054\043\056\046\001\002\000\026\030\061\032\057" +
    "\033\063\034\055\035\056\036\060\037\066\040\062\046" +
    "\064\047\065\001\002\000\034\007\044\017\036\020\047" +
    "\024\040\025\045\027\051\041\052\045\053\050\037\052" +
    "\042\053\041\054\043\056\046\001\002\000\034\007\044" +
    "\017\036\020\047\024\040\025\045\027\051\041\052\045" +
    "\053\050\037\052\042\053\041\054\043\056\046\001\002" +
    "\000\034\007\044\017\036\020\047\024\040\025\045\027" +
    "\051\041\052\045\053\050\037\052\042\053\041\054\043" +
    "\056\046\001\002\000\034\007\044\017\036\020\047\024" +
    "\040\025\045\027\051\041\052\045\053\050\037\052\042" +
    "\053\041\054\043\056\046\001\002\000\034\007\044\017" +
    "\036\020\047\024\040\025\045\027\051\041\052\045\053" +
    "\050\037\052\042\053\041\054\043\056\046\001\002\000" +
    "\004\056\102\001\002\000\034\007\044\017\036\020\047" +
    "\024\040\025\045\027\051\041\052\045\053\050\037\052" +
    "\042\053\041\054\043\056\046\001\002\000\050\005\uffd2" +
    "\006\uffd2\014\uffd2\015\uffd2\016\uffd2\022\uffd2\030\uffd2\032" +
    "\uffd2\033\uffd2\034\uffd2\035\uffd2\036\uffd2\037\uffd2\040\uffd2" +
    "\042\uffd2\043\uffd2\046\uffd2\047\uffd2\051\uffd2\001\002\000" +
    "\004\055\070\001\002\000\034\007\044\017\036\020\047" +
    "\024\040\025\045\027\051\041\052\045\053\050\037\052" +
    "\042\053\041\054\043\056\046\001\002\000\042\005\uffde" +
    "\006\uffde\014\uffde\015\uffde\016\uffde\022\uffde\032\057\033" +
    "\063\034\055\035\056\040\062\042\uffde\043\uffde\046\uffde" +
    "\047\065\051\uffde\001\002\000\004\040\071\001\002\000" +
    "\004\056\072\001\002\000\004\045\073\001\002\000\040" +
    "\007\044\017\036\020\047\024\040\025\045\027\051\041" +
    "\052\042\uffef\045\053\046\uffef\050\037\052\042\053\041" +
    "\054\043\056\046\001\002\000\030\030\061\032\057\033" +
    "\063\034\055\035\056\036\060\037\066\040\062\042\uffee" +
    "\046\uffee\047\065\001\002\000\006\042\076\046\077\001" +
    "\002\000\034\007\044\017\036\020\047\024\040\025\045" +
    "\027\051\041\052\045\053\050\037\052\042\053\041\054" +
    "\043\056\046\001\002\000\050\005\uffe6\006\uffe6\014\uffe6" +
    "\015\uffe6\016\uffe6\022\uffe6\030\uffe6\032\uffe6\033\uffe6\034" +
    "\uffe6\035\uffe6\036\uffe6\037\uffe6\040\uffe6\042\uffe6\043\uffe6" +
    "\046\uffe6\047\uffe6\051\uffe6\001\002\000\030\030\061\032" +
    "\057\033\063\034\055\035\056\036\060\037\066\040\062" +
    "\042\uffed\046\uffed\047\065\001\002\000\050\005\uffe0\006" +
    "\uffe0\014\uffe0\015\uffe0\016\uffe0\022\uffe0\030\uffe0\032\uffe0" +
    "\033\uffe0\034\uffe0\035\uffe0\036\uffe0\037\uffe0\040\062\042" +
    "\uffe0\043\uffe0\046\uffe0\047\065\051\uffe0\001\002\000\004" +
    "\045\103\001\002\000\040\007\044\017\036\020\047\024" +
    "\040\025\045\027\051\041\052\042\uffef\045\053\046\uffef" +
    "\050\037\052\042\053\041\054\043\056\046\001\002\000" +
    "\006\042\076\046\105\001\002\000\050\005\uffe7\006\uffe7" +
    "\014\uffe7\015\uffe7\016\uffe7\022\uffe7\030\uffe7\032\uffe7\033" +
    "\uffe7\034\uffe7\035\uffe7\036\uffe7\037\uffe7\040\uffe7\042\uffe7" +
    "\043\uffe7\046\uffe7\047\uffe7\051\uffe7\001\002\000\042\005" +
    "\uffdd\006\uffdd\014\uffdd\015\uffdd\016\uffdd\022\uffdd\032\057" +
    "\033\063\034\055\035\056\040\062\042\uffdd\043\uffdd\046" +
    "\uffdd\047\065\051\uffdd\001\002\000\042\005\uffdc\006\uffdc" +
    "\014\uffdc\015\uffdc\016\uffdc\022\uffdc\032\057\033\063\034" +
    "\055\035\056\040\062\042\uffdc\043\uffdc\046\uffdc\047\065" +
    "\051\uffdc\001\002\000\050\005\uffe3\006\uffe3\014\uffe3\015" +
    "\uffe3\016\uffe3\022\uffe3\030\uffe3\032\uffe3\033\063\034\uffe3" +
    "\035\056\036\uffe3\037\uffe3\040\062\042\uffe3\043\uffe3\046" +
    "\uffe3\047\065\051\uffe3\001\002\000\050\005\uffe1\006\uffe1" +
    "\014\uffe1\015\uffe1\016\uffe1\022\uffe1\030\uffe1\032\uffe1\033" +
    "\uffe1\034\uffe1\035\uffe1\036\uffe1\037\uffe1\040\062\042\uffe1" +
    "\043\uffe1\046\uffe1\047\065\051\uffe1\001\002\000\050\005" +
    "\uffe2\006\uffe2\014\uffe2\015\uffe2\016\uffe2\022\uffe2\030\uffe2" +
    "\032\uffe2\033\063\034\uffe2\035\056\036\uffe2\037\uffe2\040" +
    "\062\042\uffe2\043\uffe2\046\uffe2\047\065\051\uffe2\001\002" +
    "\000\050\005\uffdf\006\uffdf\014\uffdf\015\uffdf\016\uffdf\022" +
    "\uffdf\030\uffdf\032\uffdf\033\uffdf\034\uffdf\035\uffdf\036\uffdf" +
    "\037\uffdf\040\062\042\uffdf\043\uffdf\046\uffdf\047\065\051" +
    "\uffdf\001\002\000\050\005\uffd1\006\uffd1\014\uffd1\015\uffd1" +
    "\016\uffd1\022\uffd1\030\061\032\057\033\063\034\055\035" +
    "\056\036\060\037\066\040\062\042\uffd1\043\uffd1\046\uffd1" +
    "\047\065\051\uffd1\001\002\000\004\043\116\001\002\000" +
    "\010\003\ufff7\051\ufff7\056\ufff7\001\002\000\026\022\120" +
    "\030\061\032\057\033\063\034\055\035\056\036\060\037" +
    "\066\040\062\047\065\001\002\000\004\056\122\001\002" +
    "\000\006\021\uffea\056\uffea\001\002\000\004\044\126\001" +
    "\002\000\006\021\125\056\122\001\002\000\006\021\uffe9" +
    "\056\uffe9\001\002\000\050\005\uffd0\006\uffd0\014\uffd0\015" +
    "\uffd0\016\uffd0\022\uffd0\030\uffd0\032\uffd0\033\uffd0\034\uffd0" +
    "\035\uffd0\036\uffd0\037\uffd0\040\uffd0\042\uffd0\043\uffd0\046" +
    "\uffd0\047\uffd0\051\uffd0\001\002\000\004\055\127\001\002" +
    "\000\004\023\130\001\002\000\034\007\044\017\036\020" +
    "\047\024\040\025\045\027\051\041\052\045\053\050\037" +
    "\052\042\053\041\054\043\056\046\001\002\000\026\030" +
    "\061\032\057\033\063\034\055\035\056\036\060\037\066" +
    "\040\062\043\132\047\065\001\002\000\006\021\uffe8\056" +
    "\uffe8\001\002\000\040\007\044\017\036\020\047\024\040" +
    "\025\045\027\051\041\052\042\uffef\045\053\046\uffef\050" +
    "\037\052\042\053\041\054\043\056\046\001\002\000\034" +
    "\007\044\017\036\020\047\024\040\025\045\027\051\041" +
    "\052\045\053\050\037\052\042\053\041\054\043\056\046" +
    "\001\002\000\050\005\uffe4\006\uffe4\014\uffe4\015\uffe4\016" +
    "\uffe4\022\uffe4\030\061\032\057\033\063\034\055\035\056" +
    "\036\060\037\066\040\062\042\uffe4\043\uffe4\046\uffe4\047" +
    "\065\051\uffe4\001\002\000\006\042\076\046\137\001\002" +
    "\000\050\005\uffe5\006\uffe5\014\uffe5\015\uffe5\016\uffe5\022" +
    "\uffe5\030\uffe5\032\uffe5\033\uffe5\034\uffe5\035\uffe5\036\uffe5" +
    "\037\uffe5\040\uffe5\042\uffe5\043\uffe5\046\uffe5\047\uffe5\051" +
    "\uffe5\001\002\000\050\005\uffd6\006\uffd6\014\uffd6\015\uffd6" +
    "\016\uffd6\022\uffd6\030\uffd6\032\uffd6\033\uffd6\034\uffd6\035" +
    "\uffd6\036\uffd6\037\uffd6\040\062\042\uffd6\043\uffd6\046\uffd6" +
    "\047\065\051\uffd6\001\002\000\026\016\142\030\061\032" +
    "\057\033\063\034\055\035\056\036\060\037\066\040\062" +
    "\047\065\001\002\000\034\007\044\017\036\020\047\024" +
    "\040\025\045\027\051\041\052\045\053\050\037\052\042" +
    "\053\041\054\043\056\046\001\002\000\026\005\144\030" +
    "\061\032\057\033\063\034\055\035\056\036\060\037\066" +
    "\040\062\047\065\001\002\000\034\007\044\017\036\020" +
    "\047\024\040\025\045\027\051\041\052\045\053\050\037" +
    "\052\042\053\041\054\043\056\046\001\002\000\026\006" +
    "\146\030\061\032\057\033\063\034\055\035\056\036\060" +
    "\037\066\040\062\047\065\001\002\000\050\005\uffd5\006" +
    "\uffd5\014\uffd5\015\uffd5\016\uffd5\022\uffd5\030\uffd5\032\uffd5" +
    "\033\uffd5\034\uffd5\035\uffd5\036\uffd5\037\uffd5\040\uffd5\042" +
    "\uffd5\043\uffd5\046\uffd5\047\uffd5\051\uffd5\001\002\000\050" +
    "\005\uffd7\006\uffd7\014\uffd7\015\uffd7\016\uffd7\022\uffd7\030" +
    "\uffd7\032\uffd7\033\uffd7\034\uffd7\035\uffd7\036\uffd7\037\uffd7" +
    "\040\uffd7\042\uffd7\043\uffd7\046\uffd7\047\uffd7\051\uffd7\001" +
    "\002\000\036\007\044\017\036\020\047\024\040\025\045" +
    "\027\051\041\052\045\053\050\037\051\154\052\042\053" +
    "\041\054\043\056\046\001\002\000\026\030\061\032\057" +
    "\033\063\034\055\035\056\036\060\037\066\040\062\043" +
    "\152\047\065\001\002\000\036\007\uffec\017\uffec\020\uffec" +
    "\024\uffec\025\uffec\027\uffec\041\uffec\045\uffec\050\uffec\051" +
    "\uffec\052\uffec\053\uffec\054\uffec\056\uffec\001\002\000\026" +
    "\030\061\032\057\033\063\034\055\035\056\036\060\037" +
    "\066\040\062\043\155\047\065\001\002\000\050\005\uffd3" +
    "\006\uffd3\014\uffd3\015\uffd3\016\uffd3\022\uffd3\030\uffd3\032" +
    "\uffd3\033\uffd3\034\uffd3\035\uffd3\036\uffd3\037\uffd3\040\uffd3" +
    "\042\uffd3\043\uffd3\046\uffd3\047\uffd3\051\uffd3\001\002\000" +
    "\036\007\uffeb\017\uffeb\020\uffeb\024\uffeb\025\uffeb\027\uffeb" +
    "\041\uffeb\045\uffeb\050\uffeb\051\uffeb\052\uffeb\053\uffeb\054" +
    "\uffeb\056\uffeb\001\002\000\026\014\157\030\061\032\057" +
    "\033\063\034\055\035\056\036\060\037\066\040\062\047" +
    "\065\001\002\000\034\007\044\017\036\020\047\024\040" +
    "\025\045\027\051\041\052\045\053\050\037\052\042\053" +
    "\041\054\043\056\046\001\002\000\026\015\161\030\061" +
    "\032\057\033\063\034\055\035\056\036\060\037\066\040" +
    "\062\047\065\001\002\000\050\005\uffd4\006\uffd4\014\uffd4" +
    "\015\uffd4\016\uffd4\022\uffd4\030\uffd4\032\uffd4\033\uffd4\034" +
    "\uffd4\035\uffd4\036\uffd4\037\uffd4\040\uffd4\042\uffd4\043\uffd4" +
    "\046\uffd4\047\uffd4\051\uffd4\001\002\000\006\042\ufff1\046" +
    "\ufff1\001\002\000\006\026\165\043\164\001\002\000\010" +
    "\003\ufff6\051\ufff6\056\ufff6\001\002\000\034\007\044\017" +
    "\036\020\047\024\040\025\045\027\051\041\052\045\053" +
    "\050\037\052\042\053\041\054\043\056\046\001\002\000" +
    "\026\030\061\032\057\033\063\034\055\035\056\036\060" +
    "\037\066\040\062\043\167\047\065\001\002\000\010\003" +
    "\ufff5\051\ufff5\056\ufff5\001\002\000\010\003\ufff8\051\ufff8" +
    "\056\ufff8\001\002\000\004\043\172\001\002\000\010\002" +
    "\ufffc\003\ufffc\004\ufffc\001\002\000\010\003\ufff4\051\ufff4" +
    "\056\ufff4\001\002\000\010\003\016\051\175\056\021\001" +
    "\002\000\004\043\176\001\002\000\010\002\ufffd\003\ufffd" +
    "\004\ufffd\001\002\000\010\002\ufffb\003\ufffb\004\ufffb\001" +
    "\002\000\004\002\000\001\002\000\010\002\ufffe\003\ufffe" +
    "\004\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\177\000\010\003\004\004\003\005\006\001\001\000" +
    "\004\005\200\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\006\173\007\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\017\007\016\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\167\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\010\023\011\025\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\161\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\047\001\001\000\004\014\155\001\001\000" +
    "\006\013\147\014\150\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\140\001\001\000\004\014\137\001\001\000\002\001\001" +
    "\000\004\014\116\001\001\000\002\001\001\000\004\014" +
    "\113\001\001\000\004\014\112\001\001\000\004\014\053" +
    "\001\001\000\002\001\001\000\004\014\111\001\001\000" +
    "\004\014\110\001\001\000\004\014\107\001\001\000\004" +
    "\014\106\001\001\000\004\014\105\001\001\000\002\001" +
    "\001\000\004\014\100\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\066\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\074\014\073\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\014\077\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\012" +
    "\103\014\073\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\015\122\016\120\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\016\123\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\014\130\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\012\135\014\073\001\001\000\004\014\134" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\142" +
    "\001\001\000\002\001\001\000\004\014\144\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\014\152\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\157\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\165\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\007\167\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$CoolParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$CoolParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$CoolParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    int omerrs = 0;

    public void syntax_error(Symbol cur_token) {
        int lineno = action_obj.curr_lineno();
	String filename = action_obj.curr_filename().getString();
        System.err.print("\"" + filename + "\", line " + lineno + 
		         ": parse error at or near ");
        Utilities.printToken(cur_token);
	omerrs++;
	if (omerrs>50) {
	   System.err.println("More than 50 errors");
	   System.exit(1);
	}
    }

    public void unrecovered_syntax_error(Symbol cur_token) {
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$CoolParser$actions {

 

    int curr_lineno() {
	return ((CoolTokenLexer)parser.getScanner()).curr_lineno();
    }

    AbstractSymbol curr_filename() {
	return ((CoolTokenLexer)parser.getScanner()).curr_filename();
    }

  private final CoolParser parser;

  /** Constructor */
  CUP$CoolParser$actions(CoolParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$CoolParser$do_action(
    int                        CUP$CoolParser$act_num,
    java_cup.runtime.lr_parser CUP$CoolParser$parser,
    java.util.Stack            CUP$CoolParser$stack,
    int                        CUP$CoolParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$CoolParser$result;

      /* select the action based on the action number */
      switch (CUP$CoolParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= CASE expr OF cases ESAC 
            {
              Expression RESULT = null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Cases c = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new typcase(curr_lineno(),e,c); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= NOT expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		RESULT = new comp(curr_lineno(),e1); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= LPAREN expr RPAREN 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		RESULT = e1; 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= LBRACE block_expr RBRACE 
            {
              Expression RESULT = null;
		Expressions e1 = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		RESULT = new block(curr_lineno(),e1); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= WHILE expr LOOP expr POOL 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new loop(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expr ::= IF expr THEN expr ELSE expr FI 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e3 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new cond(curr_lineno(),e1,e2,e3); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expr ::= ISVOID expr 
            {
              Expression RESULT = null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new isvoid(curr_lineno(),e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expr ::= NEW TYPEID 
            {
              Expression RESULT = null;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new new_(curr_lineno(),t); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= BOOL_CONST 
            {
              Expression RESULT = null;
		Boolean b = (Boolean)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new bool_const(curr_lineno(),b); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= OBJECTID 
            {
              Expression RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new object(curr_lineno(),o); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= STR_CONST 
            {
              Expression RESULT = null;
		AbstractSymbol s = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new string_const(curr_lineno(),s); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= INT_CONST 
            {
              Expression RESULT = null;
		AbstractSymbol i = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new int_const(curr_lineno(),i); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr EQ expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new eq(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr LE expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new leq(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= expr LT expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new lt(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= NEG expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new neg(curr_lineno(),e1); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= expr DIV expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new divide(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= expr MULT expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new mul(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= expr MINUS expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new sub(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr PLUS expr 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new plus(curr_lineno(),e1,e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= OBJECTID ASSIGN expr 
            {
              Expression RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		RESULT = new assign(curr_lineno(),o,e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr ::= OBJECTID LPAREN expression_list RPAREN 
            {
              Expression RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new dispatch(curr_lineno(),(new object(curr_lineno(),TreeConstants.self)),o,el); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr ::= expr AT TYPEID DOT OBJECTID LPAREN expression_list RPAREN 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-7)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new static_dispatch(curr_lineno(),e1,t,o,el); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr ::= expr DOT OBJECTID LPAREN expression_list RPAREN 
            {
              Expression RESULT = null;
		Expression e1 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new dispatch(curr_lineno(),e1,o,el); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(10/*expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // case ::= OBJECTID COLON TYPEID DARROW expr SEMI 
            {
              Case RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol c = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new branch(curr_lineno(),o,c,e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(12/*case*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // cases ::= cases case 
            {
              Cases RESULT = null;
		Cases ca = (Cases)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		Case c = (Case)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = ca.appendElement(c); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(11/*cases*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // cases ::= case 
            {
              Cases RESULT = null;
		Case c = (Case)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = (new Cases(curr_lineno())).appendElement(c); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(11/*cases*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // block_expr ::= block_expr expr SEMI 
            {
              Expressions RESULT = null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = el.appendElement(e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(9/*block_expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // block_expr ::= expr SEMI 
            {
              Expressions RESULT = null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = (new Expressions(curr_lineno())).appendElement(e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(9/*block_expr*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expression_list ::= expression_list COMMA expr 
            {
              Expressions RESULT = null;
		Expressions el = (Expressions)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Expression e2 = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = el.appendElement(e2); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(8/*expression_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expression_list ::= expr 
            {
              Expressions RESULT = null;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = (new Expressions(curr_lineno())).appendElement(e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(8/*expression_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expression_list ::= 
            {
              Expressions RESULT = null;
		 RESULT = new Expressions(curr_lineno()); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(8/*expression_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // formal ::= OBJECTID COLON TYPEID 
            {
              Formal RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new formalc(curr_lineno(),o,t); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(7/*formal*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // formal_list ::= formal_list COMMA formal 
            {
              Formals RESULT = null;
		Formals fl = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		Formal f = (Formal)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = fl.appendElement(f); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(6/*formal_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // formal_list ::= formal 
            {
              Formals RESULT = null;
		Formal f = (Formal)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = (new Formals(curr_lineno())).appendElement(f); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(6/*formal_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // formal_list ::= 
            {
              Formals RESULT = null;
		 RESULT = new Formals(curr_lineno()); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(6/*formal_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // feature ::= error SEMI 
            {
              Feature RESULT = null;

              CUP$CoolParser$result = new java_cup.runtime.Symbol(5/*feature*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // feature ::= OBJECTID COLON TYPEID ASSIGN expr SEMI 
            {
              Feature RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-5)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new attr(curr_lineno(),o,t,e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(5/*feature*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // feature ::= OBJECTID COLON TYPEID SEMI 
            {
              Feature RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-3)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		 RESULT = new attr(curr_lineno(),o,t,(new no_expr(curr_lineno()))); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(5/*feature*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // feature ::= OBJECTID LPAREN formal_list RPAREN COLON TYPEID LBRACE expr RBRACE SEMI 
            {
              Feature RESULT = null;
		AbstractSymbol o = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-9)).value;
		Formals f = (Formals)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-7)).value;
		AbstractSymbol t = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Expression e = (Expression)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new method(curr_lineno(),o,f,t,e); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(5/*feature*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // dummy_feature_list ::= dummy_feature_list feature 
            {
              Features RESULT = null;
		Features fl = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		Feature f = (Feature)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = fl.appendElement(f); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(4/*dummy_feature_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // dummy_feature_list ::= feature 
            {
              Features RESULT = null;
		Feature f = (Feature)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = (new Features(curr_lineno())).appendElement(f); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(4/*dummy_feature_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // dummy_feature_list ::= 
            {
              Features RESULT = null;
		 RESULT = new Features(curr_lineno()); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(4/*dummy_feature_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // class ::= error SEMI 
            {
              class_c RESULT = null;

              CUP$CoolParser$result = new java_cup.runtime.Symbol(3/*class*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // class ::= CLASS TYPEID INHERITS TYPEID LBRACE dummy_feature_list RBRACE SEMI 
            {
              class_c RESULT = null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-6)).value;
		AbstractSymbol p = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n, p, f, curr_filename()); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(3/*class*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // class ::= CLASS TYPEID LBRACE dummy_feature_list RBRACE SEMI 
            {
              class_c RESULT = null;
		AbstractSymbol n = (AbstractSymbol)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-4)).value;
		Features f = (Features)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-2)).value;
		 RESULT = new class_c(curr_lineno(), n, 
		                   AbstractTable.idtable.addString("Object"), 
				   f, curr_filename()); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(3/*class*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // class_list ::= class_list class 
            {
              Classes RESULT = null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = cl.appendElement(c); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(2/*class_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // class_list ::= class 
            {
              Classes RESULT = null;
		class_c c = (class_c)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = (new Classes(curr_lineno())).appendElement(c); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(2/*class_list*/, RESULT);
            }
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= program EOF 
            {
              Object RESULT = null;
		programc start_val = (programc)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-1)).value;
		RESULT = start_val;
              CUP$CoolParser$result = new java_cup.runtime.Symbol(0/*$START*/, RESULT);
            }
          /* ACCEPT */
          CUP$CoolParser$parser.done_parsing();
          return CUP$CoolParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // program ::= class_list 
            {
              programc RESULT = null;
		Classes cl = (Classes)((java_cup.runtime.Symbol) CUP$CoolParser$stack.elementAt(CUP$CoolParser$top-0)).value;
		 RESULT = new programc(curr_lineno(), cl); 
              CUP$CoolParser$result = new java_cup.runtime.Symbol(1/*program*/, RESULT);
            }
          return CUP$CoolParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

